SistemaMercadoLibre/Pages/Vista/Almacenista/VistaAlmacenista.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SistemaMercadoLibre.Pages.Controlador;
using SistemaMercadoLibre.Pages.Modelo;
using System.Data.SqlClient;

namespace SistemaMercadoLibre.Pages.Vista.Almacenista
{
    public class VistaAlmacenistaModel : PageModel
    {
        public List<Audicion> lstAudicion = new List<Audicion>();
        public String errorMessage = "";
        public String successMessage = "";
        SqlConnection conn = GestionDatos.conectar();
        public void OnGet()
        {
            lstAudicion = GestionarAlmacen.obtenerListPorAlmacenar(conn);
        }

        public void OnPostAceptar()
        {
            Audicion audicion = new Audicion();
            audicion.IdAuditoria = Request.Form["idAudicion"];
            audicion.Estado = Int32.Parse(Request.Form["estado"]);
            audicion.IdVenta = Request.Form["idVenta"];

            string respuesta = GestionarAlmacen.aceptarIngresoAlmacen(conn, audicion);
            Console.WriteLine("respuesta --> " + respuesta.ToString());
            errorMessage = respuesta;
            //Actualizar Estado Producto
            lstAudicion = GestionarAuditoria.obtenerListAudicion(conn);
        }
    }
}

SistemaMercadoLibre/Pages/Vista/Auditor/VistaAudicion.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SistemaMercadoLibre.Pages.Controlador;
using SistemaMercadoLibre.Pages.Modelo;
using System.Data.SqlClient;

namespace SistemaMercadoLibre.Pages.Vista.Auditor
{
    public class VistaAudicionModel : PageModel
    {
        public List<Audicion> lstAudicion = new List<Audicion>();
        public String errorMessage = "";
        public String successMessage = "";
        SqlConnection conn = GestionDatos.conectar();
        public void OnGet()
        {
            lstAudicion = GestionarAuditoria.obtenerListAudicion(conn);
        }

        public void OnPostAceptar()
        {
            Audicion audicion = new Audicion();

            audicion.IdAuditoria = Request.Form["idAudicion"];
            audicion.Estado = Int32.Parse(Request.Form["estado"]);
            audicion.DetalleAudicion = Request.Form["detalleAudicion"];
            audicion.IdVenta = Request.Form["idVenta"];

            string respuesta = GestionarAuditoria.aceptarRechazarProductoAuditor(conn, audicion);
            Console.WriteLine("respuesta --> " + respuesta.ToString());
            errorMessage = respuesta;
            //Actualizar Estado Producto
            lstAudicion = GestionarAuditoria.obtenerListAudicion(conn);
        }
    }
}

SistemaMercadoLibre/Pages/Vista/Autorizar/AutorizarJefeAlmacen.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SistemaMercadoLibre.Pages.Controlador;
using SistemaMercadoLibre.Pages.Modelo;

namespace SistemaMercadoLibre.Pages.Vista.Autorizar
{
    public class AutorizarJefeAlmacenModel : PageModel
    {
        public List<DtoGuiasPendientes> lista = new List<DtoGuiasPendientes>();
        public String errorMessage = "";
        public String successMessage = "";
        public int ENVIAR_AUTORIZAR_ALMACEN = 11; //Constante ENVIARAUTORIZARALMACEN
        public int AUTORIZADO_JEFE_ALMACEN = 12; //Constante AUTORIZADO_JEFE_ALMACEN
        public void OnGet()
        {

            DtoGuiasPendientes dto = new DtoGuiasPendientes();
            dto.setEstadoProducto(ENVIAR_AUTORIZAR_ALMACEN);
            lista = GestionGuiasPendientes.ListarGuiasPendientes(dto);
        }
        public void OnPostRecolectar()
        {
            DtoGuiasPendientes dto = new DtoGuiasPendientes();
            dto.setIdProducto(Request.Form["txtIdProducto"].ToString());
            dto.setEstadoProducto(AUTORIZADO_JEFE_ALMACEN);
            //Modificar A ESTADO AUTORIZADO_JEFE_ALMACEN(12)
            String err = GestionGuiasPendientes.ActualizarEstadoProducto(dto);
            dto.setEstadoProducto(ENVIAR_AUTORIZAR_ALMACEN);
            //Lista estado ENVIAR_AUTORIZAR_ALMACEN(11)
            lista = GestionGuiasPendientes.ListarGuiasPendientes(dto);

            successMessage = "Producto Actualizado Correctamente.";

        }
    }
}

SistemaMercadoLibre/Pages/Vista/Autorizar/EnviarJefeAlmacen.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SistemaMercadoLibre.Pages.Controlador;
using SistemaMercadoLibre.Pages.Modelo;

namespace SistemaMercadoLibre.Pages.Vista.Autorizar
{
    public class EnviarJefeAlmacenModel : PageModel
    {
        public List<DtoGuiasPendientes> lista = new List<DtoGuiasPendientes>();
        public String errorMessage = "";
        public String successMessage = "";
        public int RECOLECTADO = 10; //Constante RECOLECTADO
        public int ENVIAR_AUTORIZAR_ALMACEN = 11; //Constante ENVIARAUTORIZARALMACEN
        public void OnGet()
        {

            DtoGuiasPendientes dto = new DtoGuiasPendientes();
            dto.setEstadoProducto(RECOLECTADO);
            lista = GestionGuiasPendientes.ListarGuiasPendientes(dto);
        }
        public void OnPostRecolectar()
        {
            DtoGuiasPendientes dto = new DtoGuiasPendientes();
            dto.setIdProducto(Request.Form["txtIdProducto"].ToString());
            dto.setEstadoProducto(ENVIAR_AUTORIZAR_ALMACEN);
            //Modificar a Estado ENVIARAUTORIZARALMACEN(11)
            String err = GestionGuiasPendientes.ActualizarEstadoProducto(dto);
            //Lista estado RECOLECTADO(10)
            dto.setEstadoProducto(RECOLECTADO);
            lista = GestionGuiasPendientes.ListarGuiasPendientes(dto);

            successMessage = "Producto Actualizado Correctamente.";

        }
    }
}

SistemaMercadoLibre/Pages/Vista/Categoria/Categoria.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SistemaMercadoLibre.Pages.Vista.Categoria
{
    public class CategoriaModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

SistemaMercadoLibre/Pages/Vista/Confirmar/ConfirmarDespacho.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SistemaMercadoLibre.Pages.Controlador;
using SistemaMercadoLibre.Pages.Modelo;

namespace SistemaMercadoLibre.Pages.Vista.Confirmar
{
    public class ConfirmarDespachoModel : PageModel
    {
        public List<DtoGuiasPendientes> lista = new List<DtoGuiasPendientes>();
        public String errorMessage = "";
        public String successMessage = "";
        public int EMPAQUE_CONFIRMADO = 13; //Constante EMPAQUE_CONFIRMADO
        public int DESPACHO_CONFIRMADO = 14; //Constante AUTORIZADO_JEFE_ALMACEN
       
        public void OnGet()
        {

            DtoGuiasPendientes dto = new DtoGuiasPendientes();
            dto.setEstadoProducto(EMPAQUE_CONFIRMADO);
            lista = GestionGuiasPendientes.ListarGuiasPendientes(dto);
        }
        public void OnPostRecolectar()
        {
            DtoGuiasPendientes dto = new DtoGuiasPendientes();
            dto.setIdProducto(Request.Form["txtIdProducto"].ToString());
            dto.setEstadoProducto(DESPACHO_CONFIRMADO);
            //Modificar a Estado DESPACHO_CONFIRMADO(14)
            String err = GestionGuiasPendientes.ActualizarEstadoProducto(dto);
            //Lista estado EMPAQUE_CONFIRMADO(13)
            dto.setEstadoProducto(EMPAQUE_CONFIRMADO);
            lista = GestionGuiasPendientes.ListarGuiasPendientes(dto);

            successMessage = "Producto Actualizado Correctamente.";

        }
    }
}

SistemaMercadoLibre/Pages/Vista/Confirmar/ConfirmarEmpaque.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SistemaMercadoLibre.Pages.Controlador;
using SistemaMercadoLibre.Pages.Modelo;

namespace SistemaMercadoLibre.Pages.Vista.Confirmar
{
    public class ConfirmarEmpaqueModel : PageModel
    {
        public List<DtoGuiasPendientes> lista = new List<DtoGuiasPendientes>();
        public String errorMessage = "";
        public String successMessage = "";
        public int AUTORIZADO_JEFE_ALMACEN = 12; //Constante AUTORIZADO_JEFE_ALMACEN
        public int EMPAQUE_CONFIRMADO = 13; //Constante EMPAQUE_CONFIRMADO
        public void OnGet()
        {

            DtoGuiasPendientes dto = new DtoGuiasPendientes();
            dto.setEstadoProducto(AUTORIZADO_JEFE_ALMACEN);
            lista = GestionGuiasPendientes.ListarGuiasPendientes(dto);
        }
        public void OnPostRecolectar()
        {
            DtoGuiasPendientes dto = new DtoGuiasPendientes();
            dto.setIdProducto(Request.Form["txtIdProducto"].ToString());
            dto.setEstadoProducto(EMPAQUE_CONFIRMADO);
            //Modificar a Estado EMPAQUE_CONFIRMADO(13)
            String err = GestionGuiasPendientes.ActualizarEstadoProducto(dto);
            //Lista estado AUTORIZADO_JEFE_ALMACEN(12)
            dto.setEstadoProducto(AUTORIZADO_JEFE_ALMACEN);
            lista = GestionGuiasPendientes.ListarGuiasPendientes(dto);

            successMessage = "Producto Actualizado Correctamente.";

        }
    }
}

SistemaMercadoLibre/Pages/Vista/Guias/DescargarGuias.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SistemaMercadoLibre.Pages.Controlador;
using SistemaMercadoLibre.Pages.Modelo;

namespace SistemaMercadoLibre.Pages.Vista.Guias
{
    public class DescargarGuiasModel : PageModel
    {
        public List<DtoGuiasPendientes> lista = new List<DtoGuiasPendientes>();
        public String errorMessage = "";
        public String successMessage = "";
        public int ALMACENADO = 9; //Constante Almacenado
        public int RECOLECTADO = 10; //Constante Recolectado
        public void OnGet()
        {
            
            DtoGuiasPendientes dto = new DtoGuiasPendientes();
            dto.setEstadoProducto(ALMACENADO);
            lista = GestionGuiasPendientes.ListarGuiasPendientes(dto);
        }
        public void OnPostRecolectar()
        {
            DtoGuiasPendientes dto = new DtoGuiasPendientes();
            dto.setIdProducto(Request.Form["txtIdProducto"].ToString());
            dto.setEstadoProducto(RECOLECTADO);
            //Modificar a Estado RECOLECTADO(10)
            String err = GestionGuiasPendientes.ActualizarEstadoProducto(dto);
            //ListarEstado ALMACENADO(9)
            dto.setEstadoProducto(ALMACENADO);
            lista = GestionGuiasPendientes.ListarGuiasPendientes(dto);

            successMessage = "Producto Actualizado Correctamente.";

        }
    }
}

SistemaMercadoLibre/Pages/Vista/Inicio/Inicio.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SistemaMercadoLibre.Pages.Vista.Inicio
{

    public class InicioModel : PageModel
    {
        string usuario = "";
        public void OnGet()
        {
        

        }
    }
}

SistemaMercadoLibre/Pages/Vista/Login/Login.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SistemaMercadoLibre.Pages.Vista.Login
{
    public class LoginModel : PageModel
    {
        public void OnGet()
        {
        }
        public IActionResult OnPost(string email, string password) {

            Console.WriteLine("test");
            Console.WriteLine(email);
            Console.WriteLine(password);


            return RedirectToPage("/Vista/Inicio/Inicio");

        }
    }
}

SistemaMercadoLibre/Pages/Vista/Recepcionista/VistaAsistenteRecepcion.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SistemaMercadoLibre.Pages.Controlador;
using SistemaMercadoLibre.Pages.Modelo;
using System.Data.SqlClient;

namespace SistemaMercadoLibre.Pages.Vista.Recepcionista
{
    public class VistaAsistenteRecepcionModel : PageModel
    {
        public List<Recepcion> lstRecepcion = new List<Recepcion>();
        public String errorMessage = "";
        public String successMessage = "";
        SqlConnection conn = GestionDatos.conectar();
        public void OnGet()
        {
            string idUsuario = HttpContext.Session.GetString("ID_USUARIO");
            lstRecepcion = GestionaRecepcion.RecepcionadosPorGenerarComprobante(conn,idUsuario);
        }

        public void OnPostAceptar()
        {
            Recepcion recepcion = new Recepcion();
            recepcion.IdRecepcion = Request.Form["idRecepcion"];
            recepcion.Estado = Int32.Parse(Request.Form["estado"]);
            recepcion.IdVenta = Request.Form["idVenta"];

            recepcion.IdUsuario = HttpContext.Session.GetString("ID_USUARIO");
            string respuesta = GestionaRecepcion.actualizarRecepcion(conn, recepcion);
            Console.WriteLine("respuesta --> " + respuesta.ToString());
            errorMessage = respuesta;
            lstRecepcion = GestionaRecepcion.RecepcionadosPorGenerarComprobante(conn, recepcion.IdUsuario);
        }
    }
}

SistemaMercadoLibre/Pages/Vista/Recepcionista/VistaRecepcion.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SistemaMercadoLibre.Pages.Controlador;
using SistemaMercadoLibre.Pages.Modelo;
using System.Data.SqlClient;

namespace SistemaMercadoLibre.Pages.Vista.Recepcionista
{
    public class VistaRecepcionModel : PageModel
    {
        //public List<Categoria> lista = new List<Categoria>();
        public List<Venta> lstVenta = new List<Venta>();
        public String errorMessage = "";
        public String successMessage = "";
        SqlConnection conn = GestionDatos.conectar();
        public Venta detalleVenta = new Venta();
        public void OnGet()
        {
            lstVenta = GestionaRecepcion.mostrarVentasEnTabla(conn);

        }

        public void OnPostAceptar()
        {
            string idVenta = Request.Form["idVenta"];
            int estado = Int32.Parse(Request.Form["estado"]);
            string observacion = Request.Form["observacion"];

            Venta venta = new Venta();
            venta.IdVenta = Request.Form["idVenta"];
            venta.Estado = Int32.Parse(Request.Form["estado"]);

            string idUsuario = HttpContext.Session.GetString("ID_USUARIO");
            string respuesta = GestionaRecepcion.actualizarEstado(conn, venta, observacion, idUsuario);
            Console.WriteLine("respuesta --> " + respuesta.ToString());
            lstVenta = GestionaRecepcion.mostrarVentasEnTabla(conn);
        }

        public void OnPostVerDetalle()
        {
            string idVenta = Request.Form["idVentaDetalle"];
            detalleVenta = GestionaRecepcion.solicitarDatosVenta(conn, idVenta);
            Console.WriteLine("respuesta --> " + detalleVenta.ToString());
            errorMessage = "Producto Recepcionado con Exito";
            lstVenta = GestionaRecepcion.mostrarVentasEnTabla(conn);

        }
    }
}

SistemaMercadoLibre/Pages/Vista/Recepcionista/VistaAsistenteRecepcion.cshtml
@page
@model SistemaMercadoLibre.Pages.Vista.Recepcionista.VistaAsistenteRecepcionModel
@{
  }
  @if (Model.errorMessage.Length > 0)
 {
    <div class='alert alert-warning alert-dismissible fade show' role='alert'>
          <strong>@Model.errorMessage</strong>
          <button type='button' class='btn-close' data-bs-dismiss='alert' arial-label='Close'></button>
    </div>

}
@if (Model.successMessage.Length > 0)
 {
    <div class='alert alert-success alert-dismissible fade show' role='alert'>
          <strong>@Model.successMessage</strong>
          <button type='button' class='btn-close' data-bs-dismiss='alert' arial-label='Close'></button>
    </div>

}
    <h2>Recepción de productos</h2>
        <ol class="breadcrumb mb-4 mt-4">
    <li class="breadcrumb-item"><a href="index.html">Emitir comprobante</a></li>
    <li class="breadcrumb-item active">Emitir comprobante</li>
        </ol>
    <div class="card">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>Emitir comprobante
        </div>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table table-hover" id="tblRecepcion" >
                        <thead>
                            <th class="text-center active">N° Orden pedido</th>
                            <th class="text-center active">Fecha modificación</th>
                            <th class="text-center active">Comprobante</th>
                            <th class="text-center active">Estado</th>
                            <th class="text-center active">Acción</th>
                        </thead>
                        <tbody>
                            @{
                            @if(Model.lstRecepcion!=null){
                            @foreach (var recepcion in Model.lstRecepcion)
                                {
                                            <tr>
                                                <td class="text-center">@recepcion.NroOrden</td>
                                                <td class="text-center">@recepcion.FechaRegistro</td>
                                                <td class="text-center">@recepcion.NumComprobante</td>
                                                <td class="text-center">
                                                @{
                                                    @switch(recepcion.Estado){
                                                        case 1: <span class="badge bg-success">Recepcionado</span>
                                                        break;
                                                        case 3: <span class="badge bg-warning">Por enviar</span>
                                                        break;
                                                    }
                                                }
                                                </td>
                                                <td class="text-center">
                                                    @{
                                                        @switch(recepcion.Estado){
                                                        case 1: 
                                                        <button type="button" class="btn btn-outline-success btn-sm" onclick="setValues('@recepcion.IdRecepcion','emitir', '@recepcion.NroOrden','@recepcion.IdVenta')"><i class="fa-solid fa-gears"></i> Emitir comprobante</button>
                                                        break;
                                                        case 3: <button type="button" class="btn btn-outline-primary btn-sm" onclick="setValues('@recepcion.IdRecepcion','enviar auditar','@recepcion.NroOrden','@recepcion.IdVenta')"><i class="fa-solid fa-paper-plane" ></i> Enviar auditar</button>
                                                        break;
                                                        }
                                                    }
                                                </td>
                                            </tr>
                                }
                            }
                                
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        </div>


        <!-- Modal -->
        <div class="modal fade" id="confirmacion" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <form method="POST">
                    <input type="hidden"  id="idRecepcion" name="idRecepcion"/>
                     <input type="hidden" id="idVenta" name="idVenta"/>
                    <input type="hidden" id="estado" name="estado"/>
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Confirmación</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-md-12">
                                <h6>¿Esta seguro de <span id="tipo"></span> para el pedido N° <span id="nroOrden"></span>?</h6>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-success" data-bs-dismiss="modal" asp-page-handler="Aceptar" >Aceptar</button>
                        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancelar</button>
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@section scripts{
    <script>
        var tablaData = $("#tblRecepcion").DataTable({
            responsive: true,
            ordering: true,
            dom: 'Bfrtip',
            "language": {
                url: "https://cdn.datatables.net/plug-ins/1.11.5/i18n/es-ES.json"
            },
            buttons: [
                'copy',
                'print',
                'excel'
            ]
        });

        function setValues(idRecepcion, tipo, nroOrden, idVenta) {
            $("#idRecepcion").val(idRecepcion);
            $("#idVenta").val(idVenta);
            $("#tipo").empty();
            $("#nroOrden").empty();
            if (tipo == "emitir") {
                $("#estado").val(3);
                $("#tipo").append("emitir comprobante");
            } else {
                $("#estado").val(4);
                $("#tipo").append("enviar auditar producto");
            }
            $("#nroOrden").append(nroOrden);
            $("#confirmacion").modal("show");
        }
    </script>
  }